### ISSUE TITLE
Navbar icons not appearing correctly : CSS under emoji-icons.css

### ISSUE THREAD

**Issue by sahuja4** [eleanorkonik/-palatinate#1]

**Comment by sahuja4** [comment]
In addition to the fonts mentioned in the main README.md, another [font](https://icomoon.io/LigatureFont.zip) needs to be installed for the navbar icons to be rendered properly

**Comment by eleanorkonik** [comment]
Ach! Thank you. It's documented in the individual .css file but I forgot to add it to the readme: adding this now, thank you.
