### ISSUE TITLE
Would be cleaner if the block embed didn't have the background shade

### ISSUE THREAD

**Issue by bibek-maharjan** [eleanorkonik/-palatinate#3]
![image](https://user-images.githubusercontent.com/76084262/126865415-0dc90a1d-9359-454f-bf24-2bcabc7e796d.png)

**Comment by eleanorkonik** [comment]
You're welcome to remove it by deleting the relevant section of the css.

I specifically added it because it helps me visually detect which things are embedded without having a hard stop at the edge that I personally find distracting, but everyone has different preferences :)
