### ISSUE TITLE
Is there a way to get rid of the vertical lines?

### ISSUE THREAD

**Issue by jaideeprana** [eleanorkonik/-palatinate#4]
This theme is simply awesome. However I want to customise it a bit and remove the vertical lines as I personally dislike them.

Is there a way to get rid of them?

![image](https://user-images.githubusercontent.com/3875065/133579878-beb1f7ba-fc15-451f-a462-f1f002e21dc5.png)

**Comment by eleanorkonik** [comment]
Sure thing! If you look for this code — https://github.com/eleanorkonik/-palatinate/blob/main/relationship-lines.css — in the palatinate.css file you can just delete it.

**Comment by jaideeprana** [comment]
Thanks @eleanorkonik :)

Let me give it a try.

**Comment by jaideeprana** [comment]
Thanks it works :)
